<?php

module_load_include('php', 'islandora', '../islandora.api');
require_once drupal_get_path('module', 'islandora_basic_collection') . '/includes/batch.inc';

/**
 * @file
 * Define hooks and menu
 */

function islandora_regenerate_dc_menu() {
  $items = array();
  $items['admin/islandora/tools/islandora_regenerate_dc'] = array(
    'title' => 'DC Regeneration',
    'page arguments' => array('islandora_regenerate_dc_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

// implement hook_islandora_datastream_ingested
function islandora_regenerate_dc_islandora_datastream_modified($object, $datastream, $params) {
  if($datastream->id == 'MODS') {
    module_load_include('inc', 'islandora_batch_derivative_trigger', 'includes/batch');
    module_load_include('module', 'xml_form_builder', 'xml_form_builder');
    islandora_batch_derivative_trigger_regenerate_dc_metadata($object, 'mods_to_dc.xsl:MODS');

    $dc_xml = simplexml_load_string($object['DC']->content);
    $namespaces = $dc_xml->getNamespaces(TRUE);
    $dc = $dc_xml->children($namespaces['dc']);
    $new_title = $dc->title;
    if ($new_title != $object->label) {
      $old_title = $object->label;
      $object->label = $new_title;
    }
  }
}
