<?php

module_load_include('php', 'islandora', '../islandora.api');
require_once drupal_get_path('module', 'islandora_basic_collection') . '/includes/batch.inc';

/**
 * @file
 * Define hooks and menu
 */

function islandora_regenerate_ds_menu() {
  $items = array();
  $items['admin/islandora/tools/islandora_regenerate_dc'] = array(
    'title' => 'DC Regeneration',
    'page arguments' => array('islandora_regenerate_dc_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

// invoke hook_islandora_datastream_ingested


function islandora_regenerate_ds_islandora_datastream_modified($pid) {
  //i need the pid somehow...
  module_load_include('inc', 'islandora_batch_derivative_trigger', 'includes/batch');
  module_load_include('inc', 'islandora_regenerate_dc', 'utils');
  module_load_include('module', 'xml_form_builder', 'xml_form_builder');

  dpm('did it run? modified');

  $obj = islandora_object_load($pid);
  islandora_batch_derivative_trigger_regenerate_dc_metadata($obj, 'mods_to_dc.xsl:MODS');

//borrowed from SFULibrary/islandora_datastream_crud
//special thanks to Mark Jordan
// Update object label from DC if specified.
  $dc = simplexml_load_string($obj['DC']->content);
  $new_title = $dc->title;
  if ($new_title != $obj->label) {
    $old_title = $obj->label;
    $obj->label = $new_title;
  }
}

islandora_regenerate_ds_islandora_datastream_modified('lsu-sc-test:5');


function islandora_regenerate_ds_islandora_datastream_purged() {
  dpm('did it run? purged');
}

