<?php

module_load_include('php', 'islandora', '../islandora.api');

/**
 * @file
 * Define hooks and menu
 */

function islandora_regenerate_ds_menu() {
  $items = array();
  $items['admin/islandora/tools/islandora_regenerate_ds'] = array(
    'title' => 'Datastream Regeneration',
    'page arguments' => array('islandora_regenerate_ds_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

// invoke hook_islandora_datastream_ingested

function islandora_regenerate_ds_islandora_datastream_modified() {
  dpm('did it run? modified');
}

function islandora_regenerate_ds_islandora_datastream_purged() {
  dpm('did it run? purged');
}
